# Generated by Django 4.1.7 on 2023-05-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images_1')),
                ('song', models.FileField(upload_to='images_1')),
            ],
        ),
    ]
