# Generated by Django 4.1.7 on 2023-05-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyndama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='music',
            name='time',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
