# Generated by Django 4.1.7 on 2023-05-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyndama', '0002_music_album_music_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('songs', models.ManyToManyField(to='tyndama.music')),
            ],
        ),
    ]
