# Generated by Django 4.1.7 on 2023-05-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyndama', '0004_playlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
